import os
import pandas as pd
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_report(dest_path: str, stats: Dict[str, Any], logs_data: List[Dict[str, Any]]):
    """
    Generates a beautifully styled, professional PDF report of DDoS security audit events.
    """
    # Create the document template
    doc = SimpleDocTemplate(
        dest_path,
        pagesize=letter,
        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    # Custom colors matching our blue/white professional theme
    primary_color = colors.HexColor("#0d6efd")
    dark_neutral = colors.HexColor("#1e293b")
    light_neutral = colors.HexColor("#f8fafc")
    border_color = colors.HexColor("#e2e8f0")
    
    # Custom styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=10
    )
    
    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=25
    )
    
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=dark_neutral,
        spaceBefore=15,
        spaceAfter=10
    )
    
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=dark_neutral
    )

    # 1. Header Section
    story.append(Paragraph("DDoS Shield: Intrusion Audit Report", title_style))
    story.append(Paragraph(f"Compiled on: {stats['date']} | Scope: {stats['scope']} | Generated by: {stats['creator']}", subtitle_style))
    
    # 2. Executive Summary Metrics Box
    story.append(Paragraph("Executive Summary Metrics", section_heading))
    summary_data = [
        [Paragraph("<b>Metric Dimension</b>", body_style), Paragraph("<b>Value Captured</b>", body_style)],
        [Paragraph("Total Packet Flows Audited", body_style), Paragraph(str(stats["total_scanned"]), body_style)],
        [Paragraph("Identified DDoS Anomalies", body_style), Paragraph(str(stats["total_anomalies"]), body_style)],
        [Paragraph("Primary Attack Vector Identified", body_style), Paragraph(stats["top_vector"], body_style)],
        [Paragraph("Global System Status", body_style), Paragraph("<b>ATTACK ACTIVE</b>" if stats["total_anomalies"] > 0 else "<b>SECURE</b>", body_style)]
    ]
    
    summary_table = Table(summary_data, colWidths=[250, 250])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), primary_color),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('BACKGROUND', (0, 1), (1, -1), light_neutral),
        ('GRID', (0, 0), (-1, -1), 1, border_color),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    # Apply white text color to headers inside TableStyle
    for i in range(2):
        summary_data[0][i].style.textColor = colors.white
        
    story.append(summary_table)
    story.append(Spacer(1, 20))
    
    # 3. Recent Anomalies Detailed Table
    story.append(Paragraph("Recent Isolated Threat Log (Audit Trail)", section_heading))
    
    # Define table column width (total 530)
    col_widths = [110, 100, 70, 160, 90]
    
    # Table headers
    table_data = [[
        Paragraph("<b>Timestamp</b>", body_style),
        Paragraph("<b>Source IP</b>", body_style),
        Paragraph("<b>Protocol</b>", body_style),
        Paragraph("<b>Classification</b>", body_style),
        Paragraph("<b>Threat Level</b>", body_style)
    ]]
    
    # Populate table rows
    for log in logs_data:
        # Style label color depending on type
        label_color = "#dc3545" if log["classification"] != "BENIGN" else "#198754"
        label_p = Paragraph(f"<font color='{label_color}'><b>{log['classification']}</b></font> ({(log['confidence']*100):.1f}%)", body_style)
        
        table_data.append([
            Paragraph(log["timestamp"], body_style),
            Paragraph(log["ip"], body_style),
            Paragraph(log["proto"], body_style),
            label_p,
            Paragraph(log["level"], body_style)
        ])
        
    # Styles for recent logs headers
    for cell in table_data[0]:
        cell.style.textColor = colors.white
        
    logs_table = Table(table_data, colWidths=col_widths)
    logs_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), dark_neutral),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, border_color),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, light_neutral])
    ]))
    
    story.append(logs_table)
    
    # Build PDF
    doc.build(story)

def generate_csv_report(dest_path: str, logs_data: List[Dict[str, Any]]):
    """
    Generates a raw CSV dump of the prediction logs.
    """
    df = pd.DataFrame(logs_data)
    df.to_csv(dest_path, index=False)
